### ISSUE TITLE
Issues launching WoW

### ISSUE THREAD

**Issue by xIGBClutchIx** [shagu/ShaguController#1]
So I just got a Steam Deck and decided to try out Classic WoW on it after I saw this addon and everything with it. Currently, I am struggling to try to get the game to even launch. 

Are there any other prerequisites or something I am missing? Currently, the game will not launch after clicking play. I am not getting any feedback at all unless I force Proton under compatibility and then it will say shortcut launch failed. All the exes and everything seem to be in the correct location.

The only "modifications" to this Steam Deck are really just installing emudeck. And I am running it in the standard read-only mode.

Here are some images of what I have:
<details>
<summary>Images</summary>

![folder](https://user-images.githubusercontent.com/975065/179149027-9883eb0b-ae50-4a48-ba55-5a0c490d702f.png)

![shortcut](https://user-images.githubusercontent.com/975065/179149038-4ddefa64-8796-4f9a-8386-94bdd7d9e2d2.png)

</details>

**Comment by shagu** [comment]
Hmm.. I have also set "Proton Experimental" in the "Compatibility" settings. Maybe that?

**Comment by xIGBClutchIx** [comment]
Yeah, that got it working by checking it under the Steam settings instead of just per game.

![dBsA6GRu](https://user-images.githubusercontent.com/975065/179212363-73b0b40e-df14-4e67-b479-4d1a79bdc756.png)
