### ISSUE TITLE
Using dpad to move cursor

### ISSUE THREAD

**Issue by PhilippeMarcotte** [shagu/ShaguController#3]
Hello! Thanks for this addon. I had a question for a possible feature. In consoleport you can use the d-pad to sort of snap the cursor to the closest "ui control". That way, you can use the dpad to accept a quest for example. Do you think it would be possible to replicate this behavior with this addon?

I mostly want to get your opinion on the feasibility of this feature. I could try implementing it myself.

Thanks!

**Comment by PhilippeMarcotte** [comment]
I mostly want to get your opinion on the feasibility of this feature. I could try implementing it myself.

**Comment by shagu** [comment]
I think for only Gossip Menus that would be possible. But in general on all elements, that would be a lot of work. As i understand it, that would require to constantly scan for all visible frames that have an OnClick function attached and build a tree based on their positions to then navigate through them. Also build blacklists for some frames that shouldn't get selected (like popping up nameplates while trying to navigate through the bag). I assume hunting and fixing all cases would be a lifetime job.

Also, you can't move the mouse in vanilla, so you would also need to implement some other sort of global indicator that tells what is selected.
