### ISSUE TITLE
Game fails to load when including the proton parameter in AutoLogin.exe

### ISSUE THREAD

**Issue by ReynoldsCahoon** [shagu/ShaguController#5]
I followed the guide and included the `--proton` in the parameters for the AutoLogin.exe but couldn't get the game to load. I resolved this by removing the `--proton` parameter and selecting Proton Experimental in the compatibility section of the game options in Steam.

**Comment by ReynoldsCahoon** [comment]
Woops, I see this was also reported in #1 
Perhaps including some updated directions in the initial readme would be helpful?

**Comment by shagu** [comment]
https://github.com/shagu/ShaguController/commit/050abdc0ca2121a9207d98f9ce0cf573835cf151
