### ISSUE TITLE
Stance changes

### ISSUE THREAD

**Issue by cholman** [shagu/ShaguController#7]
It just doesn't work with stance changes? My action bars don't change during stealth, and they also stop working.

**Comment by shagu** [comment]
Hello, 
Thanks for your report. I have indeed never played with a character that uses BonusActionButtons like Stealth or Stance bars with this addon. I just tried it and the stances are changed, but won't visually hide the below actionbar which gets easilly confusing. To solve this, I have just pushed an update that now hides the "original" actionbuttons while the "bonus" actionbuttons (stealth, stances) are in use.

It seems to be fixed now on my Lv2 Rogue :)
https://github.com/shagu/ShaguController/commit/5d3241a729441399ec0428a2429fc1fde2691565
